### ISSUE TITLE
Only shows aliases for argument 0

### ISSUE THREAD

**Issue by jedahan** [molovo/tipz#2]
For example, I have 

```sh
alias g='git'
alias gwR='git reset --hard'
```

djui/alias-tips shows **gwR**, while tipz shows **g reset --hard**

**Comment by molovo** [comment]
This is a bug. I actually had the same issue with alias-tips, which is what prompted me to develop tipz in the first place. Tipz is designed to walk backward through each word in the command to find the longest match so should definitely pick that up. I suspect it's an issue with the way the dashes are escaped in the regular expression.
